export const CREATE_CHARACTER = 'CREATE_CHARACTER';
export const READ_CHARACTER = 'READ_CHARACTER';
export const UPDATE_CHARACTER = 'UPDATE_CHARACTER';
export const DELETE_CHARACTER = 'DELETE_CHARACTER';
